# Generated by Django 5.1.7 on 2025-05-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_actuator_value_boolean_actuator_value_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='topic',
            field=models.CharField(default='sensor/null', help_text='Tópico MQTT asociado', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='topic',
            field=models.CharField(default='sensor/null', help_text='Tópico MQTT asociado', max_length=128, unique=True),
        ),
    ]
