# Generated by Django 5.1.7 on 2025-06-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_actuator_topic_sensor_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='topic',
            field=models.CharField(default='sensor/null', help_text='Tópico MQTT asociado', max_length=128),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='topic',
            field=models.CharField(default='sensor/null', help_text='Tópico MQTT asociado', max_length=128),
        ),
    ]
