# Generated by Django 5.1.7 on 2025-06-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_actuator_topic_alter_sensor_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
