# Generated by Django 5.1.7 on 2025-06-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_alter_actuator_name_alter_sensor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='store_readings',
            field=models.BooleanField(default=False, help_text='Si se desactiva, las lecturas entrantes no se almacenan en BD'),
        ),
    ]
