# Generated by Django 5.1.7 on 2025-06-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_sensor_store_readings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='store_readings',
            field=models.BooleanField(default=True, help_text='Si se desactiva, las lecturas entrantes no se almacenan en BD'),
        ),
    ]
