# Generated by Django 5.1.7 on 2025-05-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sensors', '0003_actuator_value_boolean_actuator_value_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed_actuators',
            field=models.ManyToManyField(blank=True, related_name='subscribed_profiles', to='sensors.actuator'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed_sensors',
            field=models.ManyToManyField(blank=True, related_name='subscribed_profiles', to='sensors.sensor'),
        ),
    ]
